name: Test

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Besu
        run: |
          brew tap hyperledger/besu
          brew install besu

      - name: Verify installation
        run: |
          brew list | grep -q besu || {
            echo "ERROR: Could not find Besu installed"
            exit 1
          }