name: Test

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Besu
        run: |
          brew tap hyperledger/besu
          brew install besu

      - name: Verify Besu installed
        run: |
          brew list | grep besu || {
            echo "ERROR: Could not find besu"
            exit 1
          }
      
      - name: Verify Besu version
        run: |
          VERSION=$(grep url besu.rb | sed 's|.*download/\([^/]*\).*|\1|g')
          echo "Verify version [$VERSION]"
          