name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Besu
        run: |
          brew tap hyperledger/besu
          brew install besu

      - name: Verify Besu installed
        run: |
          brew list | grep besu || {
            echo "ERROR: Could not find besu"
            exit 1
          }
      
      - name: Verify Besu version
        run: |
          LATEST_VERSION=$(grep url besu.rb | sed 's|.*download/\([^/]*\).*|\1|g')
          
          # Could not grep the line using the besu: with GitHub runner
          # So using the 'stable' word in grep which seems appear only in the line required
          INSTALLED_VERSION=$(brew info besu | grep 'stable' | sed 's|.* stable \([0-9]*\.[0-9]*\.[0-9]*\).*|\1|g')

          if [[ "$LATEST_VERSION" == "$INSTALLED_VERSION" ]]
          then
            echo "Latest version [$LATEST_VERSION] match installed version [$INSTALLED_VERSION]"
            exit 0
          else
            echo "ERROR: Latest version [$LATEST_VERSION] does not match installed version [$INSTALLED_VERSION]"
            exit 1
          fi
 