name: Test

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Besu
        run: |
          brew tap hyperledger/besu
          brew install besu

      - name: Verify Besu installed
        run: |
          brew list | grep -q besu
      
      - name: Verify Besu version
        run: |
          grep 
          