name: Test

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Besu
        run: |
          homebrew tap hyperledger/besu